- name: Run Exareme Worker
  shell: docker stack deploy -c docker-compose-worker.yml {{ hostvars[my_host]['hostname'] }}
  args:
    chdir: "{{ home_path }}Compose-Files/"
  environment:
    FEDERATION_NODE: "{{ hostvars[my_host]['hostname'] }}"
    EXAREME_IMAGE: "{{ EXAREME_IMAGE }}:{{ EXAREME_TAG }}"
    EXAREME_KEYSTORE: "{{ EXAREME_KEYSTORE }}"
    DOCKER_DATA_FOLDER: "{{ DOCKER_PATH }}"
    LOCAL_DATA_FOLDER: "{{ hostvars[my_host]['data_path'] }}"
