---
- name: Find Stacks
  shell: docker stack ls --format '{{ "{{" }}.Name{{ "}}" }}'
  register: nodeStacks
  tags:
    - exareme

- name: Remove Services From Stack
  shell: docker stack rm {{ item }} 
  with_items: 
  - "{{ nodeStacks.stdout_lines }}"
  args:
    chdir: "{{ compose_files_remote_path }}"
  tags:
    - exareme

- name: Find Portainer ID
  shell: docker service ls --filter name=mip_portainer --format '{{ "{{" }}.ID{{ "}}" }}'
  register: portainer_id
  tags:
    - portainer

- name: Remove Portainer ID
  shell: docker service rm "{{ portainer_id.stdout }}"
  register: portainer_rm
  ignore_errors: true
  tags:
    - portainer
