## DO NOT CHANGE  ##

# Key-Value Store
EXAREME_KEYSTORE: "exareme-keystore:8500"

# Docker internal folder for the Exareme data
DOCKER_DATA_FOLDER: "/root/exareme/data/"

# Portainer
PORTAINER_PORT: "9000"
PORTAINER_IMAGE: "portainer/portainer"
PORTAINER_VERSION: ":latest"
PORTAINER_DATA: "{{hostvars['master']['home_path']}}portainer"
PORTAINER_NAME: "mip-portainer"






