#                    Copyright (c) 2016-2017
#   Data Intensive Applications and Systems Labaratory (DIAS)
#            Ecole Polytechnique Federale de Lausanne
#
#                      All Rights Reserved.
#
# Permission to use, copy, modify and distribute this software and its
# documentation is hereby granted, provided that both the copyright notice
# and this permission notice appear in all copies of the software, derivative
# works or modified versions, and any portions thereof, and that both notices
# appear in supporting documentation.
#
# This code is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. THE AUTHORS AND ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE
# DISCLAIM ANY LIABILITY OF ANY KIND FOR ANY DAMAGES WHATSOEVER RESULTING FROM THE
# USE OF THIS SOFTWARE.

version: '3.2'

networks:
  net-federation:
    external:
      name: mip-federation

services:
  exareme-keystore:
    image: bitnami/consul:1.8.3
    #ports:         # Used for Debugging
    #  - target: 8500     
    #    published: 8500
    #    protocol: tcp
    #    mode: host
    environment:
      - CONSUL_BIND_INTERFACE=lo
    deploy:
      placement:
        constraints:
          - node.role == manager       # Ensures we only start on manager nodes
          - node.labels.name == ${FEDERATION_NODE}
    networks:
      - "net-federation" # Connect the docker container to the global network

  exareme-master:
    image: ${EXAREME_IMAGE}
    environment:
      - CONSULURL=${EXAREME_KEYSTORE}
      - FEDERATION_ROLE=${FEDERATION_ROLE}
      - NODE_NAME=${FEDERATION_NODE}
      - TEMP_FILES_CLEANUP_TIME=30
      - NODE_COMMUNICATION_TIMEOUT=30000        # (MILIS) NODE COMMUNICATION WILL DROP IF TIMEOUT IS PASSED
      - ENVIRONMENT_TYPE=PROD                   # TEST / DEV / PROD
    depends_on:
      - exareme-keystore
    deploy:
      placement:
        constraints:
          - node.role == manager # Ensures we only start on manager nodes
          - node.labels.name == ${FEDERATION_NODE}
    ports:
      - target: 9090     # So that we can access the Exareme REST API / interface
        published: 9090
        protocol: tcp
        mode: host
    networks:
      - "net-federation" # Connect the docker container to the global network
    volumes:
      - ${LOCAL_DATA_FOLDER}:${DOCKER_DATA_FOLDER}
