#                    Copyright (c) 2016-2016
#   Data Intensive Applications and Systems Labaratory (DIAS)
#            Ecole Polytechnique Federale de Lausanne
#
#                      All Rights Reserved.
#
# Permission to use, copy, modify and distribute this software and its
# documentation is hereby granted, provided that both the copyright notice
# and this permission notice appear in all copies of the software, derivative
# works or modified versions, and any portions thereof, and that both notices
# appear in supporting documentation.
#
# This code is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. THE AUTHORS AND ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE
# DISCLAIM ANY LIABILITY OF ANY KIND FOR ANY DAMAGES WHATSOEVER RESULTING FROM THE
# USE OF THIS SOFTWARE.

version: '2'
# the following environment variables are expected to be available when running
# docker-compose up
# - raw_data_root:      The folder containing the data files (CSV, json,...) on the
#                       swarm node host. Mapped to /datasets WITHIN the containers
# - pg_data_root:       The folder containing the PostgreSQL binary tables on the
#                       swarm node host. Mapped to /data WITHIN the containers
# - raw_admin_conf:     Nginx configuration file
# - raw_admin_htpasswd: .htpasswd configuration file
# - raw_admin_log:      Nginx directory for the logs

networks:
  net-local:
    driver: bridge
  net-federation:

services:
  exalocal:
    image:  hbpmip/exaremelocal
    networks:
      - "net-local"
    links:
      - RawEngine
    environment:
      - MASTER_FLAG=master
      - RAWUSERNAME=federation
      - RAWPASSWORD=federation
      - RAWHOST=RawEngine
      - RAWPORT=80
    ports:
      - "9090:9090"

  RawEngine:
    hostname: RawEngine
    image: "hbpmip/postgresraw"
    container_name: "raw-engine"
    restart: unless-stopped
    networks:
     - "net-local"
    expose:
     - "5432"
    volumes:
     - "${raw_data_root}:/datasets:ro"
     - "${pg_data_root}:/data:rw"
    environment:
     - POSTGRES_PORT
     - POSTGRES_USER
     - POSTGRES_PASSWORD
     - POSTGRES_DB=mip

  RawUI:
    image: "hbpmip/postgresraw-ui"
    container_name: "raw-ui"
    restart: unless-stopped
    networks:
     - "net-local"
    expose:
     - "5555"
    ports:
          - "5555:5555"
    volumes:
     - "${raw_data_root}:/datasets:ro"
     - "${pg_data_root}:/data:rw"
    links:
     - "RawEngine:raw-engine"
    environment:
     - POSTGRES_HOST=raw-engine
     - POSTGRES_PORT
     - POSTGRES_USER
     - POSTGRES_PASSWORD
     - POSTGRES_DB=mip

#  RawAdvisor:
#    image: "google/cadvisor:latest"
#    container_name: "raw-cadvisor"
#    restart: unless-stopped
#    networks:
#     - "net-local"
#    expose:
#     - "8080"
#    volumes:
#     - "/:/rootfs:ro"
#     - "/var/run:/var/run:rw"
#     - "/sys:/sys:ro"
#     - "/var/lib/docker/:/var/lib/docker:ro"

  RawAdmin:
    image: "library/nginx:alpine"
    container_name: "raw-admin"
    restart: unless-stopped
    networks:
     - "net-local"
    ports:
     - "80:80"
    volumes:
     - "${raw_admin_htpasswd}:/etc/nginx/.htpasswd:ro"
     - "${raw_admin_conf}:/etc/nginx/nginx.conf:ro"
     - "${raw_admin_log}:/var/log/nginx:rw"
    links:
     - "RawUI:raw-ui"
#    - "RawAdvisor:raw-cadvisor"
