---
- name: Get The Worker join-token
  shell: docker swarm join-token --quiet worker
  register: worker_token

- name: Remove node from the swarm that has the same hostname
  shell: docker node rm {{ my_name }}
  ignore_errors: true