---
- name: Get Hostname For Worker Node
  shell: docker node ls -f "name={{ my_name }}" --format '{{ "{{" }}.Hostname{{ "}}" }}'
  register: hostName

- name:  Add Label Name To Each Node
  shell: docker node update --label-add name={{ item }} {{ item }}
  with_items:
   - "{{ hostName.stdout_lines }}"