# Exareme Tag
EXAREME_TAG: "outputFormat"
# Exareme Image
EXAREME_IMAGE: "sofiakar/myexareme"



## Nothing to change here  ##

# Key-Value Store
EXAREME_KEYSTORE: "exareme-keystore:8500"

# Docker internal folder for the Exareme data
DOCKER_DATA_FOLDER: "/root/exareme/data/"

# Portainer
PORTAINER_PORT: "9000"
PORTAINER_IMAGE: "portainer/portainer"
PORTAINER_VERSION: ":latest"
PORTAINER_DATA: "{{hostvars['master']['home_path']}}portainer"







